version: '2'
services:
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306/tcp
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bookinfo
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/mysql.conf.d:/etc/mysql/mysql.conf.d
      - ./mysql/data:/var/lib/mysql
      - ./mysql/log:/var/log/mysql

